<?php

namespace CrazyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNews()
	{
		$qb = $this->createQueryBuilder('n')
			->orderBy('n.publication', 'DESC')
			->getQuery()
		;

		return $qb->getResult();
	}
}
