<?php

namespace CrazyBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNews()
	{
		$qb = $this->createQueryBuilder('n')
			->orderBy('n.publication', 'DESC')
			->getQuery()
		;

		return $qb->getResult();
	}

	public function getLastNews()
	{
		$qb = $this->createQueryBuilder('n')
			->orderBy('n.publication', 'DESC')
			->setMaxResults(3)
			->getQuery()
		;

		return $qb->getResult();
	}

	public function getNewsPaginator($page, $nbPerPage)
	{
		$query = $this->createQueryBuilder('n')
		->orderBy('n.publication', 'DESC')
		->getQuery()
		;

		$query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage)
		;

		// Ne pas oublier le use correspondant
		return new Paginator($query, true);
	}
}
